### ISSUE TITLE
Bug in passing vector_size parameter

### ISSUE THREAD

**Issue by MorenoLaQuatra** [dmmiller612/bert-extractive-summarizer#10]
Hi, first of all thanks for sharing your work to the research community. 

I was trying to use a custom model for the extractive summarizer, in this case I noticed a little bug in the code, specifically in the `summarizer/model_processors.py` file:

The line `self.model = BertParent(model)` should be `self.model = BertParent(model, vector_size=vector_size)` because otherwise the class throws an error even if the `vector_size` parameter is specified when instantiating the `SingleModel(model=MODEL_PATH, vector_size=vs)`

Hope it helps other people and can be resolved in the master repo.

**Comment by dmmiller612** [comment]
Hello, sorry I have been away for a bit after a big move. I should have some free time next week to push the most recent changes to pypi. This has been addressed

**Comment by dmmiller612** [comment]
Vector size is no longer needed. Should be merged in pypi
