### ISSUE TITLE
Explained variation vs number of sentences

### ISSUE THREAD

**Issue by gmolinah** [dmmiller612/bert-extractive-summarizer#100]
Hi, nice library!
I want to determine the optimal numbers of clusters/sentences by using the Elbow method, so it would be useful if i can get the explained variation of each clusterization. Is that stored in some attibute?

**Comment by dmmiller612** [comment]
This is actually a great feature suggestion. I will look at adding it this weekend.

**Comment by dmmiller612** [comment]
Supported as of pypi version 0.7.1. There is also updated documentation in the readme in how to use it.
