### ISSUE TITLE
Docker images fail to build

### ISSUE THREAD

**Issue by lubani** [dmmiller612/bert-extractive-summarizer#106]
docker build -t summary-service -f Dockerfile.service ./
Sending build context to Docker daemon  138.2kB
Step 1/10 : FROM ubuntu:18.04
 ---> 4eb8f7c43909
Step 2/10 : RUN apt-get update &&     apt-get install -y sudo     build-essential     curl     libcurl4-openssl-dev     libssl-dev     wget     python3-dev     python3-pip     libxrender-dev     libxext6     libsm6     openssl
 ---> Using cache
 ---> 6a74fb77d2f2
Step 3/10 : RUN mkdir -p /opt/service
 ---> Using cache
 ---> 21f11fd01633
Step 4/10 : COPY requirements-service.txt /opt/service
 ---> Using cache
 ---> 9578a89c27b2
Step 5/10 : COPY summarizer /opt/service/summarizer
 ---> Using cache
 ---> b192f47d9803
Step 6/10 : COPY server.py /opt/service
 ---> Using cache
 ---> 0513e1d7e0d2
Step 7/10 : WORKDIR /opt/service
 ---> Using cache
 ---> 9ec353fc33c7
Step 8/10 : RUN pip3 install --upgrade pip
 ---> Using cache
 ---> d3d7cf127c7b
Step 9/10 : RUN pip3 install -r requirements-service.txt
 ---> Running in e258847b9a60
**Collecting https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.1.0.tar.gz (from -r requirements-service.txt (line 14))
  ERROR: HTTP error 404 while getting https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.1.0.tar.gz
ERROR: Could not install requirement https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.1.0.tar.gz (from -r requirements-service.txt (line 14)) because of HTTP error 404 Client Error: Not Found for url: https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.1.0.tar.gz for URL https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.1.0.tar.gz
The command '/bin/sh -c pip3 install -r requirements-service.txt' returned a non-zero code: 1
make: *** [Makefile:6: docker-service-build] Error 1**

There is already an issue similar to mine (#96).

**Comment by macfly1202** [comment]
It’s a typo just adjust same version 2.3.0 instead of 2.1.0. It must be the same in the url … you could manually navigate to space repo to check this.

**Comment by lubani** [comment]
Thanks
