### ISSUE TITLE
Empty summary on Chinese texts

### ISSUE THREAD

**Issue by tuzcsap** [dmmiller612/bert-extractive-summarizer#108]
Hello! I'm trying to apply this model to Chinese texts. I followed steps from [issue](https://github.com/dmmiller612/bert-extractive-summarizer/issues/45): 

- changed sentence_handler.py to Chinese:

```
from spacy.lang.zh import Chinese
def __init__(self, language=Chinese):
```
- downloaded `zh_core_web_sm` model and created custom config for model and tokenizer:

````
custom_config = AutoConfig.from_pretrained('bert-base-chinese')

custom_config.output_hidden_states=True

custom_tokenizer = AutoTokenizer.from_pretrained('bert-base-chinese')

custom_model = AutoModel.from_pretrained('bert-base-chinese', config=custom_config)
````
but model generates empty string as output.

Could you, please, tell me, which steps did I miss?

**Comment by Daibao1120** [comment]
This might help.
https://geek.digiasset.org/pages/nlp/nlpinfo/bert-text-summarizer-chinese/

**Comment by tuzcsap** [comment]
@Daibao1120 Thank your for this link! The code worked fine in colab environment yet one additional precondition was required:
`pip install sentencepiece`
