### ISSUE TITLE
NameError: name 'model' is not defined

### ISSUE THREAD

**Issue by SampadaShete** [dmmiller612/bert-extractive-summarizer#110]
NameError                                 Traceback (most recent call last)
<ipython-input-6-84fb4f18e8a6> in <module>()
      2 
      3 start = time.time()
----> 4 resp = model('''
      5     The Chrysler Building, the famous art deco New York skyscraper, will be sold for a small fraction of its previous sales price.
      6     The deal, first reported by The Real Deal, was for $150 million, according to a source familiar with the deal.

NameError: name 'model' is not defined

Can anyone help with this please?

**Comment by dmmiller612** [comment]
You will need to define the model like:

```
from summarizer import Summarizer

body = 'Text body that you want to summarize with BERT'
body2 = 'Something else you want to summarize with BERT'
model = Summarizer()
model(body)
model(body2)
```
