### ISSUE TITLE
AttributeError: module 'transformers.utils.logging' has no attribute 'basicConfig'

### ISSUE THREAD

**Issue by lazarinastoy** [dmmiller612/bert-extractive-summarizer#112]
Getting this error when trying to import from summarizer import Summarizer

Log below:

from summarizer import Summarizer
from summarizer.model_processors import Summarizer, TransformerSummarizer
from summarizer.bert_parent import BertParent
 logging.basicConfig(level=logging.WARNING)
AttributeError: module 'transformers.utils.logging' has no attribute 'basicConfig'

**Comment by dmmiller612** [comment]
Newest version of bert-extractive-summarizer should resolve this issue. Feel free to reopen, if it still persists.

**Comment by mishra011** [comment]
I was also facing the same issue while running 
```
from transformers import pipeline
text_gen_pipeline = pipeline("text-generation")
```
It got fixed when I installed different transformers version and it worked for me. Below version worked for me.

```
pip install transformers==4.40.0
```
