### ISSUE TITLE
Cannot reproduce examples

### ISSUE THREAD

**Issue by jacobdanovitch** [dmmiller612/bert-extractive-summarizer#2]
```python
from summarizer import SingleModel

body = 'Text body that you want to summarize with BERT'

model = SingleModel()
model(body)
```

This produces a segmentation fault within iPython on both Ubuntu 18.04 and MacOS Mojave, and crashes Google Colab. 

Specifically, the crash occurs at `model(body)`.

**Comment by dmmiller612** [comment]
Looks like for the spacy English class, neuralconf has some issues. I'll file a ticket with them, and make a fix here. Bert-extractive-summarizer 0.1.1 should still work fine

**Comment by dmmiller612** [comment]
Actually, try installing spacy 2.1.3. It worked for me there.

**Comment by dmmiller612** [comment]
While the issue is being resolved on the neuralcoref end, I put an update in setup.py that forces spacy==2.1.3. I'll update again when the issue is fixed.
