### ISSUE TITLE
Input limit?

### ISSUE THREAD

**Issue by dzimmerman-nci** [dmmiller612/bert-extractive-summarizer#22]
I know BERT has an input token limit of 512. However, this summarizer does not have an input limit because you are looping through the sentences and embedding each one with BERT separately (assuming the sentences are <512 tokens). Is this correct?

**Comment by dmmiller612** [comment]
Yeah, I think that is correct, but I will have to double check.

**Comment by dzimmerman-nci** [comment]
Thanks. Please let me know.

**Comment by dmmiller612** [comment]
Sorry, it took me so long. It is currently a requirement of 512 tokens per sentence. It can handle any number of sentences (memory constrained of course), but the sentence needs to be less than 512 tokens.
