### ISSUE TITLE
Unable to reproduce the examples

### ISSUE THREAD

**Issue by soumyatanwar** [dmmiller612/bert-extractive-summarizer#24]
I'm running the code in Google Colab notebook. 
I made sure I installed the spacy 2.1.3 version. 

However, this is the error I'm getting says Summarizer is not callable
![image](https://user-images.githubusercontent.com/37302163/68796965-bb376280-0679-11ea-922b-08fd2e08fad6.png)

Then I tried to pass the text as an argument to Summarizer which resulted in this, I expected the argument returned to be of string type i.e. the summary text:
![image](https://user-images.githubusercontent.com/37302163/68797198-22551700-067a-11ea-8cdc-e0af1ceef022.png)

And when I tried to convert the result to a string, I got this:
![image](https://user-images.githubusercontent.com/37302163/68797562-d5257500-067a-11ea-8aaf-0d1ff26e64a4.png)

What am I getting wrong here? If you could point out if I've misunderstood something, I'd really appreciate it. If you need any other information, let me know :)

**Comment by dmmiller612** [comment]
That all should work. However, I am unaware of this google colab notebook. If you wouldn't mind pasting it here, I can take a look.

**Comment by soumyatanwar** [comment]
Google Colab is just like a Jupyter Notebook, with free GPU resources, that gets saved to Google Drive. I'm sharing a link to the Colab notebook here:

https://drive.google.com/open?id=1BncuWsyEXlPUPafqAUPwK2ausg7rvA4l

**Comment by dmmiller612** [comment]
Looks like the wrong summarizer is installed:
```
Name: summarizer
Version: 0.0.7
Summary: A text summarizer
Home-page: https://github.com/michigan-com/summarizer
Author: Eric Bower
Author-email: neurosnap@gmail.com
License: The MIT License (MIT)
Location: /usr/local/lib/python3.6/dist-packages
Requires: nltk
Required-by: 
```

this requires `pip install bert-extractice-summarizer`

**Comment by soumyatanwar** [comment]
Thanks for pointing that out! It works now :)

**Comment by rajmati-GM** [comment]
@soumyatanwar  could you please paste the sample code that worked for you here ?
