### ISSUE TITLE
Example code throwing error

### ISSUE THREAD

**Issue by rajmati-GM** [dmmiller612/bert-extractive-summarizer#26]
The sample code from the readme doesnt seem to work . Is something changed in the recent commits? Please suggest
---> 29 result = model(body, min_length=60)
        30 full = ''.join(result)
        31 print(full)

TypeError: 'Summarizer' object is not callable

**Comment by rajmati-GM** [comment]
Please suggest

**Comment by dmmiller612** [comment]
You will need to pip install Bert-extractive-summarizer. https://github.com/dmmiller612/bert-extractive-summarizer/issues/24

**Comment by rajmati-GM** [comment]
thanks

**Comment by rajmati-GM** [comment]
@dmmiller612 , did pip install Bert-extractive-summarizer and re-ran  I still get the same error.

**Comment by dmmiller612** [comment]
you will have to uninstall the original summarizer package.

**Comment by Sai-Bhavana** [comment]
@dmmiller612 how to uninstall original summarizer

**Comment by omkarhp** [comment]
@dammiller612 did you get a solution for the above thread? If yes, please share. Thanks in advance!

**Comment by dejurin** [comment]
> summarizer

`pip uninstall summarizer`

**Comment by PriyeshDave** [comment]
@omkarhp Did you get solution to the error? I am getting the same error. Would really appreciate your help
