### ISSUE TITLE
Unable to install using Anaconda

### ISSUE THREAD

**Issue by csetarun** [dmmiller612/bert-extractive-summarizer#28]
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

bert-extractive-summarizer==0.1.4

**Comment by dmmiller612** [comment]
I currently don't have the package in conda. From your conda environment, you will need to run `pip install bert-extractive-summarizer`.
