### ISSUE TITLE
No module named summarizer

### ISSUE THREAD

**Issue by Lou1sWang** [dmmiller612/bert-extractive-summarizer#30]
when i run 'from summarizer import Summarizer', there is an error said no module names summarizer.

**Comment by dmmiller612** [comment]
Make sure that you use `pip install bert-extractive-summarizer` rather than just summarizer (or make sure it isn't already installed). A lot of people have had issues with that. I may rename the base package in a future release.

**Comment by Mozoku** [comment]
That still does not solve the problem. Still getting the same error

**Comment by dmmiller612** [comment]
A good way to test is using the docker image, or starting a virtualenv from scratch. This has been common issue for a lot of people, and when I get time, I will probably change the package name.

**Comment by zhenyuan0502** [comment]
I got the error too, any update @dmmiller612

**Comment by shreyu2403** [comment]
Is there any update on this ?
I am unable to import summarizer too

**Comment by dmmiller612** [comment]
This has to do with clashing package names at installation. If you set up a virtualenv from scratch or run the docker image, you should not encounter this issue.

**Comment by shreyu2403** [comment]
I set up a completely new environment a did all the steps, still the same issue.
Could you specify if there is a specific version of the prerequisite packages?

**Comment by amodi01** [comment]
I am also facing a similar issue.

**Comment by Ayush1702** [comment]
uninstall the default summarizer package if it was installed explicitly before,
Just upgrade Bert extractive summarizer with `pip install --upgrade bert-extractive-summarizer`
import it and call, it should download a newer model
```
import torch
from summarizer import Summarizer
model = Summarizer()
```
This worked for me!

![chrome_322](https://user-images.githubusercontent.com/43087979/119885868-fb0a2600-bf4f-11eb-9709-281c6164cb1c.png)

**Comment by ghost** [comment]
I am also facing a similar issue.

**Comment by ThePipsPlug** [comment]
Me too, has anyone managed to find a solution

**Comment by Mahesh100** [comment]
Facing same issue, tried everything. Any solution on this?
