### ISSUE TITLE
Can I used this bert extractive summarizer for Myanmar Language(Burmese) news summairzation?

### ISSUE THREAD

**Issue by Soe2Lwin** [dmmiller612/bert-extractive-summarizer#31]

**Comment by dmmiller612** [comment]
It would depend on a couple of factors. One you would need a Burmese pretrained Bert model, and the other would require that spacy has Burmese in their language library. I am not too sure if either of these exist.

**Comment by Soe2Lwin** [comment]
Thank you for replying

**Comment by dmmiller612** [comment]
It looks like Bert has a pretrained multi-lingual model that includes Burmese: https://github.com/google-research/bert/blob/master/multilingual.md. You would have to load this model into the transformers bert model to properly work (They have a lot of tutorials on how to do this: https://github.com/huggingface/transformers). I didn't see the Burmese language in Spacy though.

**Comment by Soe2Lwin** [comment]
Thank you for your kind. I will try to test.
