### ISSUE TITLE
can we implement it with GPU support?

### ISSUE THREAD

**Issue by zrxbeijing** [dmmiller612/bert-extractive-summarizer#36]
Hello, I like your project very much. 
One question: how can we run the code with gpu support?

**Comment by dmmiller612** [comment]
Haven’t tried it yet. I probably would need to include the device as an argument

**Comment by jackall** [comment]
This project is just awesome! thanks, @dmmiller612, but it would be great to squeeze it to GPU, CPU takes forever to run.

**Comment by dmmiller612** [comment]
So sorry this took so long. GPU support has just been added. I will be uploading the code to pypi in the  next few hours. The current colab in the repo has an example with gpu support (If you have a cuda available, you shouldn't need to do anything on your part with the most recent code change).

**Comment by zrxbeijing** [comment]
> So sorry this took so long. GPU support has just been added. I will be uploading the code to pypi in the  next few hours. The current colab in the repo has an example with gpu support (If you have a cuda available, you shouldn't need to do anything on your part with the most recent code change).

Wow! That‘s awesome! Can’t wait to try it out!
