### ISSUE TITLE
RuntimeError: unexpected EOF, expected 10413410 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by imayachita** [dmmiller612/bert-extractive-summarizer#37]
Hi,
I tried to run the code and got this error:
```
RuntimeError: unexpected EOF, expected 10413410 more bytes. The file might be corrupted.
terminate called after throwing an instance of 'c10::Error'
  what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 INTERNAL ASSERT FAILED at /pytorch/c10/util/intrusive_ptr.h:348, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /pytorch/c10/util/intrusive_ptr.h:348)
```

Anyone experienced the same issue? Thanks!

**Comment by akhisreelibra** [comment]
> Hi,
> I tried to run the code and got this error:
> 
> ```
> RuntimeError: unexpected EOF, expected 10413410 more bytes. The file might be corrupted.
> terminate called after throwing an instance of 'c10::Error'
>   what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 INTERNAL ASSERT FAILED at /pytorch/c10/util/intrusive_ptr.h:348, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /pytorch/c10/util/intrusive_ptr.h:348)
> ```
> 
> Anyone experienced the same issue? Thanks!

I've been experiencing the same. Could the development team find any resolution.

**Comment by dmmiller612** [comment]
I’ll take a look. Very likely related to the neural coref library

**Comment by dmmiller612** [comment]
We now no longer import the coreference library by default. this should address the issue (most recent version)
