### ISSUE TITLE
Can we load the neuralcoref model offline without downloading it from the code?

### ISSUE THREAD

**Issue by KiranSaal** [dmmiller612/bert-extractive-summarizer#38]

**Comment by dmmiller612** [comment]
The only way you could do that is to download the models from huggingface and point the model path to the locally saved path.

**Comment by zaid-kamil** [comment]
could you please explain, how to pass the model path in the summarizer, 
a code example would be a great help.

**Comment by dmmiller612** [comment]
Hello Zaid,

The README has been updated with how to pass in the coreference model (if desired). You can also bring your own coreference model as well. By default, the summarizer no longer passes in the coreference model, due to the number of libraries available.
