### ISSUE TITLE
error running "pip install bert-extractive-summarizer"

### ISSUE THREAD

**Issue by RabbitJackTrade** [dmmiller612/bert-extractive-summarizer#4]
While trying the installation, I received the following:

> Collecting torch>=0.4.1 (from pytorch-pretrained-bert->bert-extractive-summarize
> r)
>   ERROR: Could not find a version that satisfies the requirement torch>=0.4.1 (f
> rom pytorch-pretrained-bert->bert-extractive-summarizer) (from versions: 0.1.2,
> 0.1.2.post1)
> ERROR: No matching distribution found for torch>=0.4.1 (from pytorch-pretrained-
> bert->bert-extractive-summarizer)

Is there a docker available?

**Comment by dmmiller612** [comment]
After work today, I will add one. There seems to be some funky issues for some when installing the pytorch-pretrained-bert library.

**Comment by RabbitJackTrade** [comment]
Any news on that? I  would really, like to try bert-extractive-summarizer, but I can't get it to run anywhere.

**Comment by dmmiller612** [comment]
I added a dockerfile that handles the installs in master. I am writing a script now that makes it easier to dynamically use, but the docker image would allow you to run what is needed.

**Comment by RabbitJackTrade** [comment]
Great! I'll try that over the weekend and let you know how it went.

**Comment by RabbitJackTrade** [comment]
Well, somewhat bad news and very good news. The docker was built "successfully" but I couldn't run python in it - at all. An attempt to install jupyter notebooks also failed.

BUT - after completing the docker, outside it everything worked like a charm! I imported bert-extractive-summarizer, loaded the model, ran the code - all without a hitch! 

Trying to explain what happened is (way) over my pay grade - but it's working now.

Thanks.
