### ISSUE TITLE
Removing elements of NLP spacy object

### ISSUE THREAD

**Issue by evanmiller29** [dmmiller612/bert-extractive-summarizer#40]
This library is bloody cool, good work mate.
Is there a way to disable some elements of the spacy NLP object to reduce memory usage?

**Comment by dmmiller612** [comment]
That's a good question. So recently, I added some capabilities that now drop coreference from the dependencies. It is optional through a class. That should remove a large bulk of the dependencies.

**Comment by dmmiller612** [comment]
Closing as stale. Since this message, we also have support for a custom sentence handler before it reaches the summarization. We also dropped requirements for coreference since it expanded the spacy model size and was causing issues with dependencies. Let me know if any other issues arise.
