### ISSUE TITLE
How to get the summarized texts' embeddings rather than getting text ?

### ISSUE THREAD

**Issue by aswin-datakalp** [dmmiller612/bert-extractive-summarizer#49]
I believe  that  the final summarised text is derived from embeddings , so is there a way where i can  directly get the summarized texts emeddings directly rather than getting the summarized text ??

Any help on this would be much helpful for my task !!

**Comment by dmmiller612** [comment]
That is a good idea for a feature. I'll try to get to it sometime soon.

**Comment by pratikghanwat7** [comment]
+1

**Comment by dmmiller612** [comment]
Added in version 0.5.0. Updated documentation in readme.
