### ISSUE TITLE
Error while importing summerizer

### ISSUE THREAD

**Issue by shubhamlekhwar** [dmmiller612/bert-extractive-summarizer#51]
I am facing the issue while importing the summarizer. Anyone faced the same issue? 
![summerizer_issue](https://user-images.githubusercontent.com/45159853/81941086-fc530400-9615-11ea-8ac4-b08d054ea131.png)

**Comment by dmmiller612** [comment]
Interesting. Do you have another summarizer library already installed (this is a common issue)?

**Comment by shaivist** [comment]
I faced the same issue and reverting to SpaCy 2.2 worked for me. Maybe you can try the same

**Comment by dmmiller612** [comment]
Support for spacy 3.0 should be addressed now. Let me know if any issues persist.
