### ISSUE TITLE
Limit the summarization length

### ISSUE THREAD

**Issue by padmalcom** [dmmiller612/bert-extractive-summarizer#52]
Hi, first of all thanks for the great project.

Is there a way to limit the output of the summarizer? We use it to display a summarization in a table which get's very ugly when text length differ a lot.

**Comment by sonnylaskar** [comment]
You can pass the parameter `ratio` as `?ratio=0.1` to define the compression expected.
To get a predictable length, you could compute ratio by considering the length of the input and the expected output length.

**Comment by dmmiller612** [comment]
Yep, the ratio parameter controls the size of the summarization.

**Comment by padmalcom** [comment]
Thank you all!
