### ISSUE TITLE
How do you calculate the number of cluster for KMeans?

### ISSUE THREAD

**Issue by Bignya1234** [dmmiller612/bert-extractive-summarizer#53]
I can see that the number of cluster is defined as this:
 k = 1 if ratio * len(self.features) < 1 else int(len(self.features) * ratio)

Can anyone explain why? What is the role of ratio here?

**Comment by dmmiller612** [comment]
The ratio is supposed to be the percentage of sentences from the body of text that you want to summarize to. The motivation came from the gensim summarization package, which also does ratios.

**Comment by chirag900** [comment]
> 
hi
can you please clarify, how the sentences are selected with ratio, suppose if a body text has 10 sentences and ratio we provide as 0.2, is it first 2 sentences are used?

Thank you
