### ISSUE TITLE
Why model picks first statement as a part of summary always

### ISSUE THREAD

**Issue by pratikghanwat7** [dmmiller612/bert-extractive-summarizer#60]
I took the example given by you and started removing the first statement and applied summarization. but each time model gives output with first statement(which was not part of earlier summaries).

**Comment by SitiBanc** [comment]
I take a look at the code and find these lines: https://github.com/dmmiller612/bert-extractive-summarizer/blob/8d6ed621ed400755255ee8a2b2b5733a2f0dbd9b/summarizer/model_processors.py#L140-L148
It's the default settings for Summarizer to use the first sentence as part of the outputs.
Set `use_first` to `False` should fix this.

**Comment by dmmiller612** [comment]
Yep! Thanks @SitiBanc. This was originally put in for news summarizations, where the first sentence is critical, regardless of the modeling.
