### ISSUE TITLE
Length of Final Summary

### ISSUE THREAD

**Issue by paulowoicho** [dmmiller612/bert-extractive-summarizer#68]
Is there a way to control the length of the generated summary? Say for example, I want a summary that is just 5 sentences

**Comment by dmmiller612** [comment]
Originally, it was designed to follow the gensim textrank, which is why it is a percentage. It shouldn't be too difficult to an exact number, though. I have been pretty busy lately, but if I get some time, I can look at adding that.

**Comment by geshan** [comment]
+1

**Comment by caramdache** [comment]
+1

**Comment by pratikghanwat7** [comment]
+1

**Comment by dmmiller612** [comment]
Updated in version 0.5.0. Updated docs in readme in how to use. Thanks for the suggestion!
