### ISSUE TITLE
How can i apply your code for French?

### ISSUE THREAD

**Issue by x0rzkov** [dmmiller612/bert-extractive-summarizer#69]
Hi @dmmiller612 and guys,

Hope you are all well !

I was wondering how do you apply models like camembert or others available at https://huggingface.co/models?filter=fr with bert-extractive-summarizer.

That would be awesome ! Ca serait super !

Thanks in advance for any insights or inputs on that.

Cheers,
X

**Comment by insop** [comment]
I think this would work.
_Note_ that coref doesn't work for non English.


```
LANG_MODEL='camembert-base''

custom_config = AutoConfig.from_pretrained(LANG_MODEL)
custom_config.output_hidden_states=True
custom_tokenizer = AutoTokenizer.from_pretrained(LANG_MODEL)
custom_model = AutoModel.from_pretrained(LANG_MODEL, config=custom_config)


model = Summarizer(custom_model=custom_model, custom_tokenizer=custom_tokenizer)
resp = model(input_text)

```

**Comment by dmmiller612** [comment]
Yep! @insop solution should do the trick. Thanks!

**Comment by x0rzkov** [comment]
Hi guys,

Thanks very much for your replies :-) Merci beaucoup

How do I apply these changes to the server instance ? 
Sorry, I am much more a gopher than a pythonista so I still struggle to make such ports.

Cheers,
X

**Comment by x0rzkov** [comment]
@dmmiller612 any ideas ? just want to test it on a couple of pages.
