### ISSUE TITLE
EOFError: Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by alexanderwong-amaris** [dmmiller612/bert-extractive-summarizer#8]
windows
new conda environment

running sample code in readme: model = SingleModel() gives this error.

ps. had to manually install pytorch as the pip install bert-extractive-summarizer produced the error specified in the other issue.

any idea whats going wrong?

**Comment by dmmiller612** [comment]
Sorry, I have been away for a bit due to a move. I am not sure what the issue is here. I am moving to the new huggingface library sometime this week. I'll update the dockerfile with the new changes.

**Comment by dmmiller612** [comment]
Closing as stale. Updated bert-summarizer should have addressed memory issues.
