### ISSUE TITLE
AttributeError: 'Summarizer' object has no attribute 'run_embeddings'

### ISSUE THREAD

**Issue by vkurpad** [dmmiller612/bert-extractive-summarizer#84]
I'm running into an issue when trying to get the embeddings for a document.

# Create a new Summarizer:
summarizer = Summarizer(
            model='bert-base-uncased',
            hidden=-2,
            reduce_option='mean'
    )
# Get embeddings
embeddings = summarizer.run_embeddings(text, num_sentences=3)

The same summarizer works when called to generate a summary
summary = summarizer(parsed, ratio=ratio, min_length=min_length, max_length=max_length)

**Comment by dmmiller612** [comment]
This was most likely an issue with the bert extractive summarizer version. The most up to date version is 0.7.1.
