### ISSUE TITLE
Multi lingual summarise

### ISSUE THREAD

**Issue by Liranbz** [dmmiller612/bert-extractive-summarizer#86]
Hi,
Is there a wat to use another model for embedding\ summarise?
I wonder if I can change the type of BERT model to a BERT-multi-lingual model and to get results in other languages.
Thank you

**Comment by dmmiller612** [comment]
I haven't worked much with multi-lingual models, but this should work with any fine tuned bert model on a given language. I know that the transformers library has a multi-lingual model that could be used here.
