### ISSUE TITLE
ERROR:pytorch_pretrained_bert.modeling:Model name 'bert-large-uncased' was not found in model name list 

### ISSUE THREAD

**Issue by Arvedek** [dmmiller612/bert-extractive-summarizer#9]
hmm.. any idea how to solve this? Full error here:

ERROR:pytorch_pretrained_bert.modeling:Model name 'bert-large-uncased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased.tar.gz' was a path or url but couldn't find any file associated to this path or url.

**Comment by Arvedek** [comment]
Even though I change all the model to 'bert-base-uncased', still having this error

**Comment by dmmiller612** [comment]
This might be due to the change in huggingface. I will look at updating the api tonight

**Comment by Arvedek** [comment]
I guess it's because the internet issue... so I download the model myself and get rid of that issue.  But I met  another one which shows like IndexError: index -2 is out of bounds for dimension 0 with size 1. Change the hidden to 2 and get it works not sure why. Btw, thanks for the reply

**Comment by dmmiller612** [comment]
Should be resolved in newest pypi version

**Comment by FBruzzesi** [comment]
@dmmiller612 Using transformers 2.8.0, spacy 2.2.3 and neuralcoref 4.0.0, I am getting the  IndexError above and cannot manage to work around it. Can it be version issue?

**Comment by dmmiller612** [comment]
what version of bert-extractive-summarizer are you using?

**Comment by FBruzzesi** [comment]
I am using  0.4.2 version

**Comment by dmmiller612** [comment]
So the above issue seems to work fine now. As for your model @FBruzzesi, do you have a link to the model you are trying to use? Long story short, the current implementation takes the second to last decoding layer as embedded output. If the model flattens the decoding layer, it would throw an error here.
